/*
 * Code written by team
 * Code created by: Yuanshi WANG, Yuhong WEI
 * Code Modified by: Yuanshi WANG, Yuhong WEI
 */
var en_garden_villa = [{
  id: 17,
  name: "Ground-breaking ceremony",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "High",
  phase: 0,
  taskSerialNumber: 0.1,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 1,
  offset: 0,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Whole house",
},{
  id: 1,
  name: "Draw wall body texture diagram",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 1,
  taskSerialNumber: 1.2,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQdd",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 10,
  offset: 2,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Whole house",
},{
  id: 2,
  name: "Wall and floor repair and leveling",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "High",
  phase: 2,
  taskSerialNumber: 2.3,
  startTime: "2021-5-7",
  endTime: "2021-5-28",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQdd",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 21,
  offset: 1,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "House walls and floor",
},{
  id: 3,
  name: "On-site axial alignment sampling",
  taskDescription: "Control lines, wall lines, finish surface lines, masonry wall materials clearly marked, plaster finish surface",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 3,
  taskSerialNumber: 3.1,
  startTime: "2021-5-29",
  endTime: "2021-5-31",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQde",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 2,
  offset: 23,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "House walls and floor",
},{
  id: 4,
  name: "Wall Masonry",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Low",
  phase: 4,
  taskSerialNumber: 4.1,
  startTime: "2021-6-1",
  endTime: "2021-6-11",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQdd",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 10,
  offset: 29,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Walls of the house",
},{
  id: 5,
  name: "Setting out of strong and weak electrical box",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 5,
  taskSerialNumber: 5.3,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHb",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 2,
  offset: 37,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Walls of the house",
},{
  id: 6,
  name: "Circuit threading",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Low",
  phase: 6,
  taskSerialNumber: 6.2,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHb",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 25,
  offset: 40,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Walls of the house",
},{
  id: 7,
  name: "Verification and acceptance of the setting out of water pipe and wires",
  taskDescription: "Client should be included",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.8,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbrn",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 25,
  offset: 40,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Walls of the house",
},{
  id: 8,
  name: "Woodworking keel construction",
  taskDescription: "Ceiling, base priming, etc.",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "High",
  phase: 7,
  taskSerialNumber: 7.1,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5Z13RlCMr5uvxkMJim9Yxui",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 35,
  offset: 55,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "",
},{
  id: 9,
  name: "Mid-term verification and acceptance",
  taskDescription: "Client should be involved in the verification. At the moment all the wooden work is supposed to be done.",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Low",
  phase: 7,
  taskSerialNumber: 7.6,
  startTime: "2021-8-4",
  endTime: "2021-8-5",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbrn",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 35,
  offset: 90,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "",
},{
  id: 10,
  name: "Leveling and puncturing",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 8,
  taskSerialNumber: 8.3,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHb",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 10,
  offset: 92,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Floor of the house",
},{
  id: 11,
  name: "Wall tile paving",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Low",
  phase: 9,
  taskSerialNumber: 9.1,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQdd",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 45,
  offset: 104,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Walls of the house",
},{
  id: 12,
  name: "Primer spraying",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 10,
  taskSerialNumber: 10.3,
  startTime: "2021-8-18",
  endTime: "2021-9-27",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQde",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 40,
  offset: 104,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "",
},{
  id: 13,
  name: "Floor installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "High",
  phase: 11,
  taskSerialNumber: 11.2,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5Z13RlCMr5uvxkMJim9Yxui",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 50,
  offset: 146,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Finished product installation",
},{
  id: 14,
  name: "Spray protection",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 12,
  taskSerialNumber: 12.2,
  startTime: "2021-11-20",
  endTime: "2021-11-30",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQde",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 10,
  offset: 198,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Paint repair",
},{
  id: 15,
  name: "Installation of intelligent furniture",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Normal",
  phase: 13,
  taskSerialNumber: 13.3,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5dDOWgGkd3ACIyC9Ow8vQdd",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 15,
  offset: 210,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Whole house",
},{
  id: 16,
  name: "Hardscaping completion verification and acceptance",
  taskDescription: "House owner involved in receiving and inspection",
  belongTo: "",
  feedback: [],
  cloudList: [],
  currentPriority: "Low",
  phase: 14,
  taskSerialNumber: 14.3,
  startTime: "2021-12-21",
  endTime: "2021-12-21",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbrn",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "None",
  duration: 1,
  offset: 229,
  location: "No.5369, Jiasong Zhong Road, Qingpu District, Shanghai",
  workingArea: "Receiving and inspection",
}]

module.exports = {
  en_garden_villa: en_garden_villa
}