var en_template = [{
  name: "Ground-breaking ceremony",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 0,
  taskSerialNumber: 0.1,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "On-site drawing handover",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 0,
  taskSerialNumber: 0.2,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
},{
  name: "On-site equipment delivery",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 0,
  taskSerialNumber: 0.3,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
},{
  name: "Product delivery",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 0,
  taskSerialNumber: 0.4,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Fill out the handover form",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 0,
  taskSerialNumber: 0.5,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Teardown and construction setting out",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 0,
  taskSerialNumber: 0.6,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Further construction setting out",
  taskDescription: "Make sure the technical parameters drawings of the wall and the material technical parameters are inplace.",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 1,
  taskSerialNumber: 1.1,
  startTime: "2021-5-6",
  endTime: "2021-5-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
},{
  name: "Draw wall body texture diagram",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 1,
  taskSerialNumber: 1.2,
  startTime: "2021-5-6",
  endTime: "2021-5-7",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Removal of surface plaster layer and putty layer",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 2,
  taskSerialNumber: 2.1,
  startTime: "2021-5-7",
  endTime: "2021-5-28",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 21,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
},{
  name: "Wall demolition, clearance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 2,
  taskSerialNumber: 2.2,
  startTime: "2021-5-7",
  endTime: "2021-5-28",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 21,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
},{
  name: "Wall and floor repair and leveling",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 2,
  taskSerialNumber: 2.3,
  startTime: "2021-5-7",
  endTime: "2021-5-28",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 21,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
},{
  name: "Floor leveling verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 2,
  taskSerialNumber: 2.4,
  startTime: "2021-5-28",
  endTime: "2021-5-28",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 21,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
}, {
  name: "On-site axial alignment sampling",
  taskDescription: "控制线、建墙线、完成面线、砌墙材质标清楚，抹灰完成面",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 3,
  taskSerialNumber: 3.1,
  startTime: "2021-5-29",
  endTime: "2021-5-31",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
}, {
  name: "Sampling confirmation",
  taskDescription: "Client and design party should be involved in and check if the construction on wall meets requirement.",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 3,
  taskSerialNumber: 3.2,
  startTime: "2021-5-31",
  endTime: "2021-5-31",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "House walls and floor",
}, {
  name: "Wall Masonry",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 4,
  taskSerialNumber: 4.1,
  startTime: "2021-6-1",
  endTime: "2021-6-11",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Wall patching",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 4,
  taskSerialNumber: 4.2,
  startTime: "2021-6-1",
  endTime: "2021-6-11",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
},{
  name: "Wall plastering",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 4,
  taskSerialNumber: 4.3,
  startTime: "2021-6-1",
  endTime: "2021-6-11",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
},{
  name: "Verification and acceptance of wall masonry",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 4,
  taskSerialNumber: 4.4,
  startTime: "2021-6-11",
  endTime: "2021-6-11",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Construction line placement",
  taskDescription: "水平线、吊顶标高、吊顶造型尺寸、护墙尺寸、瓷砖完成面、柜子尺寸、空调内机位置尺寸、风口位置尺寸",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 5,
  taskSerialNumber: 5.1,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Setting out of switch and socket light position",
  taskDescription: "Fill the socket light position according to the site setting out sample",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 5,
  taskSerialNumber: 5.2,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Setting out of strong and weak electrical box",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 5,
  taskSerialNumber: 5.3,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Strong and weak wire alignment placement",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 5,
  taskSerialNumber: 5.4,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Water supply and drainage water line positioning and placement",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 5,
  taskSerialNumber: 5.5,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Setting out of bathroom",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 5,
  taskSerialNumber: 5.6,
  startTime: "2021-6-12",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Confirmation on setting out",
  taskDescription: "Needs the participation of client and design party, to confirm on the height of the ceiling, the location of the walls, and the setting out of strong current and weak current",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 5,
  taskSerialNumber: 5.7,
  startTime: "2021-6-14",
  endTime: "2021-6-14",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 2,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Plumbing and trenching",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.1,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Circuit threading",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 6,
  taskSerialNumber: 6.2,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Circuit Wiring",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 6,
  taskSerialNumber: 6.3,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Power distribution box installation",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.4,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
},{
  name: "Drainage construction",
  taskDescription: "Locate the water pipe and wires",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.5,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls and floor of the house",
},{
  name: "Plumbing and electrical circuit protection",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 6,
  taskSerialNumber: 6.6,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Installation of air conditioning and other equipment",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 6,
  taskSerialNumber: 6.7,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Verification and acceptance of the setting out of water pipe and wires",
  taskDescription: "Client should be included",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.8,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Wall punching",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.9,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Verification and acceptance of punching the wall",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 6,
  taskSerialNumber: 6.10,
  startTime: "2021-6-15",
  endTime: "2021-7-10",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 25,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Woodworking keel construction",
  taskDescription: "Ceiling, base priming, etc.",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 7,
  taskSerialNumber: 7.1,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Build foundation steel frame",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 7,
  taskSerialNumber: 7.2,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Woodworking sealing board",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 7,
  taskSerialNumber: 7.3,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Down light opening",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 7,
  taskSerialNumber: 7.4,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Plaster line installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 7,
  taskSerialNumber: 7.5,
  startTime: "2021-6-30",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Mid-term verification and acceptance",
  taskDescription: "Client should be involved in the verification. At the moment all the wooden work is supposed to be done.",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 7,
  taskSerialNumber: 7.6,
  startTime: "2021-8-4",
  endTime: "2021-8-4",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 35,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Waterproofing of bathrooms ",
  taskDescription: "Test whether the floor of the bathroom could contain water that is added intentionally for a long time",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 8,
  taskSerialNumber: 8.1,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Bathroom",
}, {
  name: "Floor heating laying",
  taskDescription: "Pressing test",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 8,
  taskSerialNumber: 8.2,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Floor of the house",
}, {
  name: "Leveling and puncturing",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 8,
  taskSerialNumber: 8.3,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Floor of the house",
}, {
  name: "Puncturing verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 8,
  taskSerialNumber: 8.4,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Floor of the house",
}, {
  name: "Floor heating leveling",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 8,
  taskSerialNumber: 8.5,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Floor of the house",
}, {
  name: "Floor heating leveling verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 8,
  taskSerialNumber: 8.6,
  startTime: "2021-8-6",
  endTime: "2021-8-16",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Floor of the house",
}, {
  name: "Wall tile paving",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 9,
  taskSerialNumber: 9.1,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Floor tiling",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 9,
  taskSerialNumber: 9.2,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Window sill plate threshold stone paving",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 9,
  taskSerialNumber: 9.3,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Tiling verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 9,
  taskSerialNumber: 9.4,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Tiling protection",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 9,
  taskSerialNumber: 9.5,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Protection verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 9,
  taskSerialNumber: 9.6,
  startTime: "2021-8-18",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 45,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Walls of the house",
}, {
  name: "Oiler anti-cracking treatment",
  taskDescription: "Anti-rust, anti-crack, leveling, base film rolling",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 10,
  taskSerialNumber: 10.1,
  startTime: "2021-8-18",
  endTime: "2021-9-27",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 40,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Putty Batching Sanding",
  taskDescription: "Anti-rust, anti-crack, leveling, base film rolling",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 10,
  taskSerialNumber: 10.2,
  startTime: "2021-8-18",
  endTime: "2021-9-27",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 40,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Primer spraying",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 10,
  taskSerialNumber: 10.3,
  startTime: "2021-8-18",
  endTime: "2021-9-27",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 40,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Wallpaper base film installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 10,
  taskSerialNumber: 10.4,
  startTime: "2021-8-18",
  endTime: "2021-9-27",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 40,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Oiler's foundation verificaiton and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 10,
  taskSerialNumber: 10.5,
  startTime: "2021-8-27",
  endTime: "2021-9-27",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 40,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "",
}, {
  name: "Air conditioning and floor heating commissioning",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 11,
  taskSerialNumber: 11.1,
  startTime: "2021-9-22",
  endTime: "2021-9-22",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Floor installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 11,
  taskSerialNumber: 11.2,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Floor protection",
  taskDescription: "Special protective film, all around minus 20 cm reserved for footing installation",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 11,
  taskSerialNumber: 11.3,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Protection verification and acceptance",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 11,
  taskSerialNumber: 11.4,
  startTime: "2021-10-2",
  endTime: "2021-10-2",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Overall woodwork installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 11,
  taskSerialNumber: 11.5,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Stair surface installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 11,
  taskSerialNumber: 11.6,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Cabinet installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 11,
  taskSerialNumber: 11.7,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Downlight installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 11,
  taskSerialNumber: 11.8,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Air conditioning air outlet installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 11,
  taskSerialNumber: 11.9,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Woodwork protection",
  taskDescription: "The edge of the floor is sealed tightly with paper.",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 11,
  taskSerialNumber: 11.10,
  startTime: "2021-9-29",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Protection verification and acceptance",
  taskDescription: "Take photos and upload",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 11,
  taskSerialNumber: 11.11,
  startTime: "2021-11-18",
  endTime: "2021-11-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 50,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Finished product installation",
}, {
  name: "Oiler's Putty Repair",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 12,
  taskSerialNumber: 12.1,
  startTime: "2021-11-20",
  endTime: "2021-11-30",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Paint repair",
}, {
  name: "Spray protection",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 12,
  taskSerialNumber: 12.2,
  startTime: "2021-11-20",
  endTime: "2021-11-30",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Paint repair",
}, {
  name: "Emulsion paint spraying",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 12,
  taskSerialNumber: 12.3,
  startTime: "2021-11-20",
  endTime: "2021-11-30",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 10,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Paint repair",
}, {
  name: "Verification and acceptance of emulsion paint",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 12,
  taskSerialNumber: 12.4,
  startTime: "2021-11-30",
  endTime: "2021-11-30",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Paint repair",
}, {
  name: "Art Paint Construction",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 13,
  taskSerialNumber: 13.1,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Switch, socket and light strip installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 13,
  taskSerialNumber: 13.2,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Installation of intelligent furniture",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 13,
  taskSerialNumber: 13.3,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Bathroom installation and commissioning",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 13,
  taskSerialNumber: 13.4,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "House cleaning",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 13,
  taskSerialNumber: 13.5,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Wallpaper hard cover installation",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 13,
  taskSerialNumber: 13.6,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Gluing closure",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 13,
  taskSerialNumber: 13.7,
  startTime: "2021-12-2",
  endTime: "2021-12-17",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 15,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Whole house",
}, {
  name: "Pre-verification and pre-acceptance and timely rectification",
  taskDescription: "Project manager involved in receiving and inspection",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 14,
  taskSerialNumber: 14.1,
  startTime: "2021-12-18",
  endTime: "2021-12-18",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Receiving and inspection",
}, {
  name: "Cleaning after preliminary completion.",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "Normal",
  phase: 14,
  taskSerialNumber: 14.2,
  startTime: "2021-12-19",
  endTime: "2021-12-19",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Receiving and inspection",
}, {
  name: "Hardscaping completion verification and acceptance",
  taskDescription: "House owner involved in receiving and inspection",
  belongTo: "",
  feedback: [],
  currentPriority: "Low",
  phase: 14,
  taskSerialNumber: 14.3,
  startTime: "2021-12-21",
  endTime: "2021-12-21",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Receiving and inspection",
}, {
  name: "Soft furnishings set-up",
  taskDescription: "",
  belongTo: "",
  feedback: [],
  currentPriority: "High",
  phase: 0,
  taskSerialNumber: 15.1,
  startTime: "2021-12-23",
  endTime: "2021-12-24",
  participant: "o_jxV5TAqQjBnhn2BVwEBhfBHbro",
  supervisor: "o_jxV5cv5StM3IW4L-4obHf50dY4",
  state: 0,
  constructionRequirements: "",
  duration: 1,
  location: "Room 409, Building A, Tomson Riviera Lane 28, Huayuan Shiqiao Road, Pudong New Area, Shanghai",
  workingArea: "Soft furnishings set-up",
}];


module.exports = {
  en_template: en_template
}
